#!/bin/sh
if [ "$1" = "reinstall" ]; then
    export ZXB_REINSTALL=true    
fi

dir="$(dirname "$0")"
set -e
cd "$dir"
if [ ! -d "$dir/.zxb/node_modules" ] || [ "$ZXB_REINSTALL" = "true" ]; then
    curl https://raw.githubusercontent.com/bunkerventure/zxb/main/install.sh | sh -
fi

cd "$dir/.zxb/"
mise install --quiet
eval "$(mise activate bash)"
bun run --install=auto "./zxb.ts" "$@"